#** This code generator (written in C) is used to auto-generate top module Verilog codes (parameterizable in the number of qubits) of quantum Fourier transform (QFT) circuit based on serial-parallel FPGA emulation architecture. Detailed descriptions of the implementation can be found in our paper (An FPGA-Based Quantum Computing Emulation Framework Based on Serial-Parallel Architecture).

all:
	gcc scale_qft.c -o scale_qft -lm
