#** Theoretical background of quantum Fourier transform (QFT) algorithm and descriptions of its circuit model can be found in our paper (An FPGA-Based Quantum Computing Emulation Framework Based on Serial-Parallel Architecture).

all:
	gcc qft.c -o qft -lm
