#** According to Gottesman-Knill theorem [11], stabilizer gates namely Hadamard, Phase, and CNOT (controlled-NOT) gates as well as single-qubit measurement in the computational basis can be simulated efficiently on a classical computer. Stabilizer circuits composed exclusively of stabilizer/Clifford gates.

all:
	gcc stabilizer_circuit.c -o stabilizer_circuit -lm
